let global = {
    actionSimple : new Map([
        ['INF', 0],
        ['Kills', 1],
        ['Bounties', 2],
        ['Bonds', 3],
        ['Explo', 4],
        ['Killbonds', 5],
        ['Sold', 21],
        ['Bought', 23],
        ['Organic', 24],
        ['S&R', 25],
    ]),
    actionComplex : new Map([
        ['INT', 6],
        ['SCT', 7],
        ['Ground', 8],
        ['Ship', 9],
        ['xLG', 10],
        ['xMG', 11],
        ['xHG', 12],
        ['xVHG', 13],
        ['x?G', 14],
        ['xLS', 15],
        ['xMS', 16],
        ['xHS', 17],
        ['xVHS', 18],
        ['x?S', 19],
        ['x?A', 20],
        ['xLP', 27],
        ['xMP', 28],
        ['xHP', 29],
        ['xVHP', 30],
    ]),
    bgsActionAmount : 32,
    summary : new Map(),
    erroredLogs : [],
    actionSummaries : [
        ' INF completed.\n',
        ' kill(s) against this faction.\n',
        'M bounties claimed.\n',
        'M bonds claimed.\n',
        'M exploration data sold.\n',
        'M against other factions.\n',
        ' Thargoid interceptor(s) killed.\n',
        ' Thargoid scout(s) killed.\n',
        ' on-foot mission(s) failed.\n',
        ' ship mission(s) failed.\n',
        ' low on-foot CZ(s) done.\n',
        ' medium on-foot CZ(s) done.\n',
        ' high on-foot CZ(s) done.\n',
        ' very high on-foot CZ(s) done.\n',
        ' unknown difficulty of on-foot CZ(s) done.\n',
        ' low ship CZ(s) done.\n',
        ' medium ship CZ(s) done.\n',
        ' high ship CZ(s) done.\n',
        ' very high ship CZ(s) done.\n',
        ' unknown difficulty of ship CZ(s) done.\n',
        ' AX CZ(s) done.\n',
        't of cargo sold with ',
        'M profit.\n',
        't of cargo bought.\n',
        'M organic data sold.\n',
        ' pods of Search and Rescue handed in with ',
        'M profit.\n',
        ' low ship Power CZ(s) done.\n',
        ' medium ship Power CZ(s) done.\n',
        ' high ship Power CZ(s) done.\n',
        ' very high ship Power CZ(s) done.\n',
        ' optional objectives done.\n',
    ],
};
module.exports = { global };