let global = {
    actionSimple : new Map([
        ['INF' , 0],
        ['Kills' , 1],
        ['Bounties' , 2],
        ['Bonds' , 3],
        ['Explo' , 4],
        ['Trade' , 5],
    ]),
    actionComplex : new Map([
        ['INT' , 6],
        ['SCT' , 7], 
        ['Ground' , 8],
        ['Ship' , 9],
        ['xLG' , 10],
        ['xMG' , 11],
        ['xHG' , 12],
        ['xVHG', 13],
        ['x?G' , 14],
        ['xLS' , 15],
        ['xMS' , 16],
        ['xHS' , 17],
        ['xVHS', 18],
        ['x?S' , 19],
        ['x?A' , 20],
    ]),
    bgsActionAmount : 22,
    summary : new Map(),
    erroredLogs : [],
    actionSummaries : [
        ' INF completed.\n',
        ' kill(s) against this faction.\n',
        'M bounties claimed.\n',
        'M bonds claimed.\n',
        'M exploration data sold.\n',
        'M profit from trade.\n',
        ' Thargoid interceptor(s) killed.\n',
        ' Thargoid scout(s) killed.\n',
        ' on-foot mission(s) failed.\n',
        ' ship mission(s) failed.\n',
        ' low on-foot CZ(s) done.\n',
        ' medium on-foot CZ(s) done.\n',
        ' high on-foot CZ(s) done.\n',
        ' very high on-foot CZ(s) done.\n',
        ' unknown difficulty of on-foot CZ(s) done.\n',
        ' low ship CZ(s) done.\n',
        ' medium ship CZ(s) done.\n',
        ' high ship CZ(s) done.\n',
        ' very high ship CZ(s) done.\n',
        ' unknown difficulty of ship CZ(s) done.\n',
        ' AX CZ(s) done.\n',
        ' optional objectives done.\n'
    ]
};
module.exports = { global };